name: barangay_buy
description: "BarangayBuy Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  flutterfire_cli: ^1.3.1
  cloud_firestore: ^5.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Title.png
    - assets/images/background.png
    - assets/images/Logo.png
    - assets/images/back-square.png
    - assets/images/notification.png
    - assets/images/location.png
    - assets/images/megaphone.png
    - assets/images/user.png
    - assets/images/addanounce.png
    - assets/images/noannounce.png
    - assets/images/UserCircle.png
    - assets/images/Trash.png
    - assets/images/arrow-up.png
    - assets/images/arrow-down.png
  fonts:
    - family: SofiaSansCondensed
      fonts:
        - asset: assets/fonts/SofiaSansCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/SofiaSansCondensed-BoldItalic.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed-SemiBold.ttf
        - asset: assets/fonts/Roboto_Condensed-BoldItalic.ttf

flutter_native_splash:
  color: "#FF6B35"
  android_12:
    color: "#FF6B35"         
    icon_background_color: "#FF6B35"
  android: true
  ios: true
  web: false